# Generated by Django 2.2 on 2019-04-30 19:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.IntegerField()),
                ('ifsc_code', models.CharField(max_length=200)),
                ('branch_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('sex', models.IntegerField()),
                ('is_married', models.BooleanField(default=False)),
                ('No_of_Degrees', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Footprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_balance', models.IntegerField()),
                ('pay_0', models.IntegerField(default=-1)),
                ('pay_1', models.IntegerField(default=-1)),
                ('pay_2', models.IntegerField(default=-1)),
                ('pay_3', models.IntegerField(default=-1)),
                ('pay_4', models.IntegerField(default=-1)),
                ('pay_5', models.IntegerField(default=-1)),
                ('bill_amt1', models.IntegerField(default=0)),
                ('bill_amt2', models.IntegerField(default=0)),
                ('bill_amt3', models.IntegerField(default=0)),
                ('bill_amt4', models.IntegerField(default=0)),
                ('bill_amt5', models.IntegerField(default=0)),
                ('bill_amt6', models.IntegerField(default=0)),
                ('bill_amt7', models.IntegerField(default=0)),
                ('bill_amt8', models.IntegerField(default=0)),
                ('bill_amt9', models.IntegerField(default=0)),
                ('bill_amt10', models.IntegerField(default=0)),
                ('bill_amt11', models.IntegerField(default=0)),
                ('bill_amt12', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='customers.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='CreditScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=500)),
                ('footprint_updated', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='customers.Profile')),
            ],
        ),
    ]
